# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arackaldir.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -30, 1041, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 331, 71))
        self.label_2.setObjectName("label_2")
        self.arackaldir = QtWidgets.QTableWidget(self.centralwidget)
        self.arackaldir.setGeometry(QtCore.QRect(210, 110, 501, 341))
        self.arackaldir.setObjectName("arackaldir")
        self.arackaldir.setColumnCount(4)
        self.arackaldir.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.arackaldir.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.arackaldir.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.arackaldir.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.arackaldir.setHorizontalHeaderItem(3, item)
        self.aracgoster = QtWidgets.QPushButton(self.centralwidget)
        self.aracgoster.setGeometry(QtCore.QRect(680, 490, 111, 41))
        self.aracgoster.setObjectName("aracgoster")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 480, 121, 21))
        self.label_3.setObjectName("label_3")
        self.aracikaldir = QtWidgets.QPushButton(self.centralwidget)
        self.aracikaldir.setGeometry(QtCore.QRect(280, 527, 101, 31))
        self.aracikaldir.setObjectName("aracikaldir")
        self.aracplaka = QtWidgets.QLineEdit(self.centralwidget)
        self.aracplaka.setGeometry(QtCore.QRect(260, 480, 113, 22))
        self.aracplaka.setObjectName("aracplaka")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ffffff;\">    ARAÇ KALDIR</span></p></body></html>"))
        item = self.arackaldir.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Araç Marka"))
        item = self.arackaldir.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Araç Model"))
        item = self.arackaldir.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Araç Plaka"))
        item = self.arackaldir.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Araç Km"))
        self.aracgoster.setText(_translate("MainWindow", "Göster"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Araç Plaka :</span></p></body></html>"))
        self.aracikaldir.setText(_translate("MainWindow", "Aracı Kaldır"))
