# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1041, 731))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desktop-wallpaper-asif-on-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-logo-mercedes-dark-thumbnail.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 70, 521, 91))
        self.label_2.setObjectName("label_2")
        self.yoneticigiris = QtWidgets.QPushButton(self.centralwidget)
        self.yoneticigiris.setGeometry(QtCore.QRect(430, 430, 191, 51))
        self.yoneticigiris.setObjectName("yoneticigiris")
        self.kullanicigiris = QtWidgets.QPushButton(self.centralwidget)
        self.kullanicigiris.setGeometry(QtCore.QRect(430, 510, 191, 51))
        self.kullanicigiris.setObjectName("kullanicigiris")
        self.uyeol = QtWidgets.QPushButton(self.centralwidget)
        self.uyeol.setGeometry(QtCore.QRect(430, 590, 191, 51))
        self.uyeol.setObjectName("uyeol")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#ffffff;\">C&amp;E RENT A CAR</span></p></body></html>"))
        self.yoneticigiris.setText(_translate("MainWindow", "Yönetici Girişi"))
        self.kullanicigiris.setText(_translate("MainWindow", "Kullanıcı Girişi"))
        self.uyeol.setText(_translate("MainWindow", "Üye Ol"))
