# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kiradakiaraclar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -40, 1021, 681))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(294, 30, 391, 61))
        self.label_2.setObjectName("label_2")
        self.kiradakiaraclar = QtWidgets.QTableWidget(self.centralwidget)
        self.kiradakiaraclar.setGeometry(QtCore.QRect(60, 120, 871, 361))
        self.kiradakiaraclar.setObjectName("kiradakiaraclar")
        self.kiradakiaraclar.setColumnCount(7)
        self.kiradakiaraclar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.kiradakiaraclar.setHorizontalHeaderItem(6, item)
        self.goster = QtWidgets.QPushButton(self.centralwidget)
        self.goster.setGeometry(QtCore.QRect(690, 520, 131, 41))
        self.goster.setObjectName("goster")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ffffff;\">KİRADAKİ ARAÇLAR</span></p></body></html>"))
        item = self.kiradakiaraclar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Araç Marka"))
        item = self.kiradakiaraclar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Araç Model"))
        item = self.kiradakiaraclar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Araç Plaka"))
        item = self.kiradakiaraclar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kiralayan Ad"))
        item = self.kiradakiaraclar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kiralayan Soyad"))
        item = self.kiradakiaraclar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gün"))
        item = self.kiradakiaraclar.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fiyat"))
        self.goster.setText(_translate("MainWindow", "Göster"))
