# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullaniciprofil.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kullaniciad = QtWidgets.QLabel(self.centralwidget)
        self.kullaniciad.setGeometry(QtCore.QRect(-20, -40, 851, 651))
        self.kullaniciad.setText("")
        self.kullaniciad.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.kullaniciad.setScaledContents(True)
        self.kullaniciad.setObjectName("kullaniciad")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 361, 101))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 240, 55, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 320, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 400, 151, 31))
        self.label_5.setObjectName("label_5")
        self.kullanicigetir = QtWidgets.QPushButton(self.centralwidget)
        self.kullanicigetir.setGeometry(QtCore.QRect(370, 490, 93, 28))
        self.kullanicigetir.setObjectName("kullanicigetir")
        self.kullaniciad_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.kullaniciad_2.setGeometry(QtCore.QRect(410, 240, 141, 31))
        self.kullaniciad_2.setObjectName("kullaniciad_2")
        self.kullanicisoyad = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanicisoyad.setGeometry(QtCore.QRect(410, 320, 141, 31))
        self.kullanicisoyad.setObjectName("kullanicisoyad")
        self.kullanicikulladi = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanicikulladi.setGeometry(QtCore.QRect(410, 400, 141, 31))
        self.kullanicikulladi.setObjectName("kullanicikulladi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ffffff;\">KULLANICI PROFİL</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Ad :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Soyad :</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Kullanıcı Adı :</span></p></body></html>"))
        self.kullanicigetir.setText(_translate("MainWindow", "Getir"))
