# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanicigiris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -40, 831, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desktop-wallpaper-asif-on-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-logo-mercedes-dark-thumbnail.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(154, 40, 471, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 360, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 420, 121, 21))
        self.label_4.setObjectName("label_4")
        self.kullanicigirisyap = QtWidgets.QPushButton(self.centralwidget)
        self.kullanicigirisyap.setGeometry(QtCore.QRect(370, 487, 111, 41))
        self.kullanicigirisyap.setObjectName("kullanicigirisyap")
        self.kullanicikulladi = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanicikulladi.setGeometry(QtCore.QRect(460, 360, 141, 31))
        self.kullanicikulladi.setObjectName("kullanicikulladi")
        self.kullanicisifre = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanicisifre.setGeometry(QtCore.QRect(460, 420, 141, 31))
        self.kullanicisifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.kullanicisifre.setObjectName("kullanicisifre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; font-style:italic; color:#ffffff;\">KULLANICI GİRİŞ PANELİ</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Kullanıcı Adı :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Şifre :</span></p></body></html>"))
        self.kullanicigirisyap.setText(_translate("MainWindow", "Giriş Yap"))
