# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanici.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -30, 1091, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 621, 131))
        self.label_2.setObjectName("label_2")
        self.kullaniciprofil = QtWidgets.QPushButton(self.centralwidget)
        self.kullaniciprofil.setGeometry(QtCore.QRect(290, 250, 461, 31))
        self.kullaniciprofil.setObjectName("kullaniciprofil")
        self.arackirala = QtWidgets.QPushButton(self.centralwidget)
        self.arackirala.setGeometry(QtCore.QRect(290, 360, 461, 31))
        self.arackirala.setObjectName("arackirala")
        self.aracteslim = QtWidgets.QPushButton(self.centralwidget)
        self.aracteslim.setGeometry(QtCore.QRect(290, 470, 461, 31))
        self.aracteslim.setObjectName("aracteslim")
        self.sikayet = QtWidgets.QPushButton(self.centralwidget)
        self.sikayet.setGeometry(QtCore.QRect(290, 570, 461, 31))
        self.sikayet.setObjectName("sikayet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-style:italic; color:#ffffff;\">C&amp;E RENT A CAR KULLANICI PANELİ</span></p></body></html>"))
        self.kullaniciprofil.setText(_translate("MainWindow", "PROFİL"))
        self.arackirala.setText(_translate("MainWindow", "ARAÇ KİRALA"))
        self.aracteslim.setText(_translate("MainWindow", "ARAÇ TESLİM ET"))
        self.sikayet.setText(_translate("MainWindow", "ŞİKAYET"))
