# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sikayetkutusu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -40, 1001, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 391, 81))
        self.label_2.setObjectName("label_2")
        self.sikayetgonder = QtWidgets.QPushButton(self.centralwidget)
        self.sikayetgonder.setGeometry(QtCore.QRect(570, 480, 93, 28))
        self.sikayetgonder.setObjectName("sikayetgonder")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 410, 55, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 470, 121, 41))
        self.label_4.setObjectName("label_4")
        self.ad = QtWidgets.QLineEdit(self.centralwidget)
        self.ad.setGeometry(QtCore.QRect(420, 420, 131, 31))
        self.ad.setObjectName("ad")
        self.soyad = QtWidgets.QLineEdit(self.centralwidget)
        self.soyad.setGeometry(QtCore.QRect(420, 480, 131, 31))
        self.soyad.setObjectName("soyad")
        self.sikayet = QtWidgets.QLineEdit(self.centralwidget)
        self.sikayet.setGeometry(QtCore.QRect(190, 120, 481, 261))
        self.sikayet.setObjectName("sikayet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ffffff;\">ŞİKAYET KUTUSU</span></p></body></html>"))
        self.sikayetgonder.setText(_translate("MainWindow", "Gönder"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Ad :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Soyad :</span></p></body></html>"))
