# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sikayetler.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -70, 911, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 301, 41))
        self.label_2.setObjectName("label_2")
        self.sikayetler = QtWidgets.QTableWidget(self.centralwidget)
        self.sikayetler.setGeometry(QtCore.QRect(260, 160, 371, 351))
        self.sikayetler.setObjectName("sikayetler")
        self.sikayetler.setColumnCount(3)
        self.sikayetler.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sikayetler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sikayetler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sikayetler.setHorizontalHeaderItem(2, item)
        self.goster = QtWidgets.QPushButton(self.centralwidget)
        self.goster.setGeometry(QtCore.QRect(580, 540, 121, 41))
        self.goster.setObjectName("goster")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">ŞİKAYETLER</span></p></body></html>"))
        item = self.sikayetler.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.sikayetler.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Şikayet"))
        item = self.sikayetler.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Soyad"))
        self.goster.setText(_translate("MainWindow", "Göster"))
