# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yonetici.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -40, 1091, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("75515051-dark-background-with-spotlights-light-studio.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 661, 101))
        self.label_2.setObjectName("label_2")
        self.aracekle = QtWidgets.QPushButton(self.centralwidget)
        self.aracekle.setGeometry(QtCore.QRect(280, 250, 461, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("desktop-wallpaper-asif-on-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-mercedes-mercedes-benz-logo-mercedes-dark-thumbnail.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aracekle.setIcon(icon)
        self.aracekle.setObjectName("aracekle")
        self.arackaldir = QtWidgets.QPushButton(self.centralwidget)
        self.arackaldir.setGeometry(QtCore.QRect(280, 400, 461, 31))
        self.arackaldir.setIcon(icon)
        self.arackaldir.setObjectName("arackaldir")
        self.kiradakiaraclar = QtWidgets.QPushButton(self.centralwidget)
        self.kiradakiaraclar.setGeometry(QtCore.QRect(280, 330, 461, 31))
        self.kiradakiaraclar.setIcon(icon)
        self.kiradakiaraclar.setObjectName("kiradakiaraclar")
        self.yoneticiprofil = QtWidgets.QPushButton(self.centralwidget)
        self.yoneticiprofil.setGeometry(QtCore.QRect(280, 170, 461, 31))
        self.yoneticiprofil.setIcon(icon)
        self.yoneticiprofil.setObjectName("yoneticiprofil")
        self.aracguncelle = QtWidgets.QPushButton(self.centralwidget)
        self.aracguncelle.setGeometry(QtCore.QRect(280, 470, 461, 31))
        self.aracguncelle.setIcon(icon)
        self.aracguncelle.setObjectName("aracguncelle")
        self.sikayetler = QtWidgets.QPushButton(self.centralwidget)
        self.sikayetler.setGeometry(QtCore.QRect(280, 550, 461, 31))
        self.sikayetler.setIcon(icon)
        self.sikayetler.setObjectName("sikayetler")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic; color:#ffffff;\">C&amp;E RENT A CAR YÖNETİCİ PANELİ</span></p></body></html>"))
        self.aracekle.setText(_translate("MainWindow", "Araç Ekle"))
        self.arackaldir.setText(_translate("MainWindow", "Araç Kaldır"))
        self.kiradakiaraclar.setText(_translate("MainWindow", "Kiradaki Araçlar"))
        self.yoneticiprofil.setText(_translate("MainWindow", "Profil"))
        self.aracguncelle.setText(_translate("MainWindow", "Araç Güncelle"))
        self.sikayetler.setText(_translate("MainWindow", "Şikayetler"))
